cachelib/redis.py

Without this the redis import will fail on py2

Fix usage of redis cache on py2 fixes #4

---

cachelib/file.py

When the threshold is set to zero, the update_count method returns without updates.  However, in the initialisation, the file list is still created.  This file list calculation is useless if the update_count is to return immediately, yet it has the potential to slow the initialisation significantly if there are many files.
This PR avoids the call to update_count and list_dir in the init, if the threshold is zero.  I did not want to make this modification in the list_dir method just in case others are using it for a different purpose.

Avoid unnecessary file count for zero threshold

---

cachelib/file.py

FileSystemCache.Set fails on windows with OSError 
`
line 158, in set
os.rename(tmp, filename)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 
on windows os.rename raises OSError if the dst file already exist. 
`
it is because of `os.rename`. on windows it throws OSError if the dst exists. 
it is suggested to use `os.replace` if we intend to overwrite the destination file

issue: FileSystemCache.Set fails on windows with OSError

---

CHANGES.rst
src/cachelib/file.py
src/cachelib/redis.py
src/cachelib/simple.py
src/cachelib/uwsgi.py

From [picke docs performance section](https://docs.python.org/3/library/pickle.html#performance) and [pickle source](https://github.com/python/cpython/blob/5b22dd87aa39087f07987f788a0bbd2464e2a8b5/Lib/pickle.py#L1348-L1352) importing cPickle directly isn't necessary for python 3 and will raise `ModuleNotFoundError`, so the code now imports pickle normally and cPickle will be transparently imported.

Remove explicit CPickle import

---

src/cachelib/_compat.py

Since only python 3 is supported, there's no need for the [version check](https://github.com/pallets/cachelib/compare/master...northernSage:remove-compat-py-version-check?expand=1#diff-581477a589825efc3fd695c3302ab5d33d5204edd2fa176e2f81251e78a3eb25L4) in `_compat.py` anymore.

Remove python version check in _compat.py

---

CHANGES.rst
src/cachelib/memcached.py

[cachelib.MemcachedCache.inc](https://github.com/pallets/cachelib/blob/master/src/cachelib/memcached.py#L151) and [cachelib.MemcachedCache.dec](https://github.com/pallets/cachelib/blob/master/src/cachelib/memcached.py#L155) were not initializing entries to delta or -delta as specified in the [cachelib.BaseCahe](https://github.com/pallets/cachelib/blob/master/src/cachelib/base.py#L20) interface.

Adjust MemcachedCache inc and dec methods to initialize entries as specified by Basecache

---

src/cachelib/file.py

As described in #20, the file count was not being updated after `os.remove()` in `FileSystemCache`.

Fix file count not being updated in FileSystemCache.get and FileSystemCache.has

---

.github/workflows/tests.yaml
tests/conftest.py
tests/test_redis_cache.py
tox.ini

This fixes the missing external dependencies in CI for tests in `tests.yml` worflow. Also had to make some other adjustments like which port redis was listening on (CI complaining that the default port was already in use) and have pytest capture sys.out/err since streams are handled a bit different in CI apparently.
Edit:

Fix CI tests workflow

---

CHANGES.rst

Add missing changelog regarding dropping py2 support.

Add missing changelog for py2 being dropped

---

tests/conftest.py

`hookwrapper=True` is not necessary for `pytest_sessionfinish ` and it's actually incompatible with the hook itself. See [docs](https://docs.pytest.org/en/6.2.x/reference.html#pytest.hookspec.pytest_sessionfinish) for details on this.

Remove hookwrapper=True from pytest_sessionfinish

---

CHANGES.rst
src/cachelib/__init__.py

Our 0.2.0 release 🎉 
**Change Summary**
_Public_
- Fix `cachelib.FileSystemCache.set` wrongfully considering value overrides on existing keys as new cache entries  #15
- `cachelib.Simplecache` and `cachelib.FileSystemCache` will now first remove expired entries, followed by removal of older entries when cleaning up #26
- Fix file count was not being updated in `FileSystemCache.get` and `FileSystemCache.has` after removals (`os.remove`) in `FileSystemCache`. #33
- When attempting to access non-existent entries with `Memcached`, these will now be initialized with a given value delta as specified in `BaseCache` #31
- Support for python 2 has been dropped. The supported releases are now python 3.6 and above.
_Internal_
- Test suite added with current code coverage around `90%` #25
- New …

Release 0.2.0

---

CHANGES.rst
src/cachelib/file.py
tests/test_file_system_cache.py

Optimize pruning and fix entry counting bug in FileSystemCache

---

CHANGES.rst
src/cachelib/__init__.py
src/cachelib/file.py
tests/test_file_system_cache.py

Handle EOFError in FileSystemCache

---

CHANGES.rst
src/cachelib/file.py
tests/test_file_system_cache.py

`FileSystemCache.get` and `FileSystemCache.has` will now only **get** and check if the current cache state **has** keys, respectively, as their names imply. I have kept the file deletion logic to the pruning stage and to the explicit removal methods `FileSystemCache.clear` and `FileSystemCache.delete`, only. This makes for a better separation of concerns. 
We also handle `FileNotFoundError` differently in `FileSystemCache.has`. If the file does not exist that means the key does not exist, so it was either not set or has been removed, we return `False` in both cases.

Separate cache file deletion from query logic

---

README.rst

Update link to pip documentation in README.rst from https://pip.pypa.io/en/stable/quickstart/ to https://pip.pypa.io/en/stable/getting-started/

Change: pip link

---

CHANGES.rst
src/cachelib/__init__.py

Our 0.3.0 release 🎉 
**Change summary**:
-   Optimize `FileSystemCache` prunning functionality
-   Fix bug in `FileSystemCache` where entries would not be removed
when total count was over threshold and entry count would be lost
-   `FileSystemCache` will now log system-related exceptions
-   Removal of expired entries in `FileSystemCache` will only be
triggered if the total number of entries is over the defined
`threshhold` when attempting to `FileSystemCache.set`.
`FileSystemCache.get` and `FileSystemCache.has` will still
return `None` and `False` (respectively) for expired entries
but they will not remove the entry files. All removals will now
be conducted at pruning time or explicitly with `clear` and
`delete`.

Released 0.3.0

---

CHANGES.rst
src/cachelib/file.py

Following #62 
We are now silently ignoring `FileNotFound` in all methods except `FilesystemCache.set`. Since a temporary file is created for the new cache entry, `FileNotFound` being raised means something is not ok and it should be logged.

Ignore FileNotFound in FilesystemCache

---

.github/workflows/tests.yaml
CHANGES.rst
src/cachelib/base.py
src/cachelib/memcached.py
src/cachelib/redis.py
src/cachelib/simple.py
src/cachelib/uwsgi.py
tests/common.py
tests/test_base_cache.py
tests/test_interface_uniformity.py
tests/test_simple_cache.py

Following #61
Uniformize existing interface and type hints
- ~`get`~ (already ok)
Implement missing optional methods
Changes to API

Uniformize API

---

tests/conftest.py

Following #36 
Add startup callback to following fixtures:

add xprocess startup callbacks to redis and memcached fixtures

---

CHANGES.rst
setup.cfg
src/cachelib/file.py
src/cachelib/redis.py
src/cachelib/serializers.py
src/cachelib/simple.py
src/cachelib/uwsgi.py
tests/test_file_system_cache.py
tests/test_redis_cache.py
tests/test_simple_cache.py
tests/test_uwsgi_cache.py

Some initial work following #11

Configurable Serialization

---

CHANGES.rst
src/cachelib/__init__.py

Our 0.5.0 release 🎉 
This release adds configurable serialization to `cachelib` #63

Release 0.5.0

---

CHANGES.rst
src/cachelib/file.py
tests/test_file_system_cache.py

support for different hashing methods in FileSystemCache

---

CHANGES.rst
src/cachelib/__init__.py

Our 0.6.0 release 🎉 
**Change Summary**
- A custom ``hash_method`` may now be provided to ``FileSystemCache`` for
hashing keys. #107 
- Fix ``PermissionError`` issue with ``FileSystemCache`` on Windows. #111

Release 0.6.0

---

CHANGES.rst
src/cachelib/__init__.py

Our 0.7.0 release 🎉 
**Change summary**
- ``FileSystemCache`` now stores universal expiration timestamps using python's ``struct`` module.
- Drop support for Python 3.6

release 0.7.0

---

src/cachelib/serializers.py

As said in #73, `inc` and `dec` operations are not being used at the redis layer so it seems like unnecessary complexity to treat integer data types differently from others.

remove unused data type check in default redis serializer

---

CHANGES.rst
src/cachelib/redis.py

Fix redis cache add without timeout

---

CHANGES.rst
src/cachelib/file.py

This has originally been proposed as fix in flask-caching. See [the original issue](https://github.com/pallets-eco/flask-caching/issues/309) for more details.

Support for Windows when creating FileSystemCache

---

CHANGES.rst
src/cachelib/redis.py
tests/test_interface_uniformity.py
tests/test_redis_cache.py

Following https://github.com/pallets-eco/flask-caching/issues/362, as it is, `cachelib.RedisCache` internally uses a single client for reading&writing, making it harder to use with subclasses with separate read and write clients such as [flask_caching.backends.rediscache.RedisSentinelCache](https://github.com/pallets-eco/flask-caching/blob/master/src/flask_caching/backends/rediscache.py#L121).

Improve RedisCache compatibility with flask-caching

---

CHANGES.rst
src/cachelib/file.py

Improve error message for non str keys in FileSystemCache._get_filename
